/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planning/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["planning_options_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planning/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planning_preview_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["process_case_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["process_case_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["mission_update"];
        trace?: never;
    };
    "/api/v1/processes/{id}/actions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["process_case_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{id}/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["process_document_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{id}/documents/{document_pk}/content/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["process_document_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{id}/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["process_case_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/mission-orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mission_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/mission-orders/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mission_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proposal_list"];
        put?: never;
        post: operations["proposal_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proposal_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["proposal_update"];
        trace?: never;
    };
    "/api/v1/proposals/{id}/decision/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposal_decision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{id}/resubmit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposal_resubmit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Expose the current session and seed the CSRF cookie for unsafe calls. */
        get: operations["session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tasks_partial_update"];
        trace?: never;
    };
    "/api/v1/tasks/{id}/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_observations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_progress_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["team_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["team_employee_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `submit` - submit
         *     * `abandon` - abandon
         *     * `claim` - claim
         *     * `takeover` - takeover
         *     * `send_to_signature` - send_to_signature
         *     * `request_correction` - request_correction
         *     * `reject` - reject
         *     * `sign` - sign
         *     * `complete_distribution` - complete_distribution
         *     * `complete_fleet` - complete_fleet
         *     * `place_legal_hold` - place_legal_hold
         *     * `release_legal_hold` - release_legal_hold
         * @enum {string}
         */
        ActionEnum: "submit" | "abandon" | "claim" | "takeover" | "send_to_signature" | "request_correction" | "reject" | "sign" | "complete_distribution" | "complete_fleet" | "place_legal_hold" | "release_legal_hold";
        /**
         * @description * `accept` - accept
         *     * `reject` - reject
         * @enum {string}
         */
        DecisionEnum: "accept" | "reject";
        DocumentUpload: {
            revision: number;
            kind: components["schemas"]["KindEnum"];
            /** Format: uri */
            file: string;
        };
        /**
         * @description * `terms_of_reference` - Termes de référence
         *     * `invitation` - Invitation
         *     * `ticket` - Billet de transport
         *     * `order_draft` - Projet d'ordre de mission
         *     * `other` - Autre pièce
         * @enum {string}
         */
        KindEnum: "terms_of_reference" | "invitation" | "ticket" | "order_draft" | "other";
        Mission: {
            mission_type: components["schemas"]["MissionTypeEnum"];
            destination: string;
            purpose: string;
            itinerary?: string;
            transport_mode?: string;
            transport_company?: string;
            /** Format: date */
            departure_date: string;
            /** Format: date */
            return_date: string;
            funding_source?: string;
            costs_covered?: string;
            /** @default false */
            vehicle_required: boolean;
            vehicle_details?: string;
            participant_ids?: number[];
            /** @default  */
            official_number: string;
        };
        /**
         * @description * `domestic` - Mission nationale
         *     * `international` - Mission internationale
         * @enum {string}
         */
        MissionTypeEnum: "domestic" | "international";
        Observation: {
            revision: number;
            message: string;
        };
        PatchedMissionUpdate: {
            mission_type?: components["schemas"]["MissionTypeEnum"];
            destination?: string;
            purpose?: string;
            itinerary?: string;
            transport_mode?: string;
            transport_company?: string;
            /** Format: date */
            departure_date?: string;
            /** Format: date */
            return_date?: string;
            funding_source?: string;
            costs_covered?: string;
            /** @default false */
            vehicle_required: boolean;
            vehicle_details?: string;
            participant_ids?: number[];
            /** @default  */
            official_number: string;
            revision?: number;
        };
        /** @description Shared, server-validated assignment schedule. */
        PatchedProposalUpdate: {
            /** Format: date */
            start_date?: string;
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
            title?: string;
            description?: string;
            action_id?: number | null;
            calendar_id?: number;
            revision?: number;
        };
        /** @description Shared, server-validated assignment schedule. */
        PatchedTaskUpdate: {
            /** Format: date */
            start_date?: string;
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
            revision?: number;
            title?: string;
            description?: string;
            action_id?: number | null;
        };
        PlanningPreview: {
            calendar_id: number;
            /** Format: date */
            start_date: string;
            source: components["schemas"]["SourceEnum"];
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
        };
        ProcessAction: {
            revision: number;
            action: components["schemas"]["ActionEnum"];
            note?: string;
            confirmation?: string;
            checklist?: {
                [key: string]: boolean;
            };
        };
        Progress: {
            revision: number;
            /** Format: date */
            entry_date: string;
            percentage: number;
            /** @default  */
            note: string;
            /** @default false */
            blocked: boolean;
        };
        /** @description Shared, server-validated assignment schedule. */
        ProposalCreate: {
            /** Format: date */
            start_date: string;
            /** Format: date */
            due_date: string;
            /** Format: decimal */
            estimated_work_days: string;
            title: string;
            description: string;
            action_id?: number | null;
            calendar_id?: number;
        };
        ProposalDecision: {
            revision: number;
            decision: components["schemas"]["DecisionEnum"];
            /** @default  */
            reason: string;
        };
        ProposalResubmit: {
            revision: number;
        };
        /**
         * @description * `workload` - workload
         *     * `due` - due
         * @enum {string}
         */
        SourceEnum: "workload" | "due";
        /** @description Shared, server-validated assignment schedule. */
        TaskCreate: {
            /** Format: date */
            start_date: string;
            /** Format: date */
            due_date: string;
            /** Format: decimal */
            estimated_work_days: string;
            title: string;
            description: string;
            employee_id: number;
            action_id?: number | null;
            calendar_id?: number;
        };
        Transition: {
            revision: number;
            transition: components["schemas"]["TransitionEnum"];
            /** @default  */
            reason: string;
        };
        /**
         * @description * `validate` - validate
         *     * `reject` - reject
         *     * `close_early` - close_early
         * @enum {string}
         */
        TransitionEnum: "validate" | "reject" | "close_early";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_retrieve: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    planning_options_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    planning_preview_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningPreview"];
                "application/x-www-form-urlencoded": components["schemas"]["PlanningPreview"];
                "multipart/form-data": components["schemas"]["PlanningPreview"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    process_case_list: {
        parameters: {
            query?: {
                box?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    process_case_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mission_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMissionUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMissionUpdate"];
                "multipart/form-data": components["schemas"]["PatchedMissionUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    process_case_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessAction"];
                "application/x-www-form-urlencoded": components["schemas"]["ProcessAction"];
                "multipart/form-data": components["schemas"]["ProcessAction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    process_document_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["DocumentUpload"];
                "multipart/form-data": components["schemas"]["DocumentUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    process_document_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_pk: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    process_case_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    mission_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Mission"];
                "application/x-www-form-urlencoded": components["schemas"]["Mission"];
                "multipart/form-data": components["schemas"]["Mission"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mission_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalCreate"];
                "multipart/form-data": components["schemas"]["ProposalCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProposalUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProposalUpdate"];
                "multipart/form-data": components["schemas"]["PatchedProposalUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_decision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecision"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalDecision"];
                "multipart/form-data": components["schemas"]["ProposalDecision"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_resubmit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalResubmit"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalResubmit"];
                "multipart/form-data": components["schemas"]["ProposalResubmit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskCreate"];
                "multipart/form-data": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTaskUpdate"];
                "multipart/form-data": components["schemas"]["PatchedTaskUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_observations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Observation"];
                "application/x-www-form-urlencoded": components["schemas"]["Observation"];
                "multipart/form-data": components["schemas"]["Observation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_progress_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Progress"];
                "application/x-www-form-urlencoded": components["schemas"]["Progress"];
                "multipart/form-data": components["schemas"]["Progress"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
                "application/x-www-form-urlencoded": components["schemas"]["Transition"];
                "multipart/form-data": components["schemas"]["Transition"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    team_overview: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    team_employee_detail: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
