/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agenda/draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["agenda_draft_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agenda/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agenda_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agenda/versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agenda_versions_retrieve"];
        put?: never;
        post: operations["agenda_versions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agenda/versions/{id}/pdf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agenda_versions_pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["availability_retrieve"];
        put?: never;
        post: operations["availability_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["availability_partial_update"];
        trace?: never;
    };
    "/api/v1/availability/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["availability_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read and edit the current user's own profile details. */
        get: operations["my_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read and edit the current user's own profile details. */
        patch: operations["my_profile_update"];
        trace?: never;
    };
    "/api/v1/planning/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["planning_options_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planning/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planning_preview_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proposal_list"];
        put?: never;
        post: operations["proposal_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proposal_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["proposal_update"];
        trace?: never;
    };
    "/api/v1/proposals/{id}/decision/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposal_decision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{id}/resubmit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposal_resubmit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Expose the current session and seed the CSRF cookie for unsafe calls. */
        get: operations["session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Complete the mandatory replacement of a temporary password. */
        post: operations["session_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-management/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_management_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-recurrences/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["task_recurrences_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tasks_partial_update"];
        trace?: never;
    };
    "/api/v1/tasks/{id}/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_observations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_progress_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/bulk-delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks_bulk_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["team_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["team_employee_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List and create institution-managed accounts. */
        get: operations["user_list"];
        put?: never;
        /** @description List and create institution-managed accounts. */
        post: operations["user_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read and update one account and its calculated organization fields. */
        get: operations["user_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read and update one account and its calculated organization fields. */
        patch: operations["user_update"];
        trace?: never;
    };
    "/api/v1/users/{id}/activation-link/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send the existing one-time activation link for a new account. */
        post: operations["users_activation_link_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/collaborators/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read or replace one user's direct primary collaborators. */
        get: operations["users_collaborators_retrieve"];
        /** @description Read or replace one user's direct primary collaborators. */
        put: operations["users_collaborators_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deactivate or reactivate a retained account. */
        post: operations["users_deactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deactivate or reactivate a retained account. */
        post: operations["users_reactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/temporary-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate and disclose one temporary password once. */
        post: operations["users_temporary_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/bulk-action/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply one audited account action to at most one visible page. */
        post: operations["users_bulk_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Expose active organization choices for the user editor. */
        get: operations["user_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["visits_retrieve"];
        put?: never;
        post: operations["visits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{id}/departure/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["visits_departure_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `deactivate` - deactivate
         *     * `delete` - delete
         * @enum {string}
         */
        ActionEnum: "deactivate" | "delete";
        /**
         * @description * `programs` - programs
         *     * `administration` - administration
         * @enum {string}
         */
        AgendaDirectionEnum: "programs" | "administration";
        Availability: {
            employee_id: number;
            kind: components["schemas"]["AvailabilityKindEnum"];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** @default  */
            note: string;
        };
        /**
         * @description * `leave` - Congé
         *     * `absence` - Absence
         *     * `mission` - Mission
         * @enum {string}
         */
        AvailabilityKindEnum: "leave" | "absence" | "mission";
        /** @enum {unknown} */
        BlankEnum: "";
        Cancel: {
            revision: number;
            reason: string;
        };
        CollaboratorReplacement: {
            employee_id: number;
            supervisor_id: number;
        };
        CollaboratorUpdate: {
            collaborator_ids: number[];
            replacements?: components["schemas"]["CollaboratorReplacement"][];
            /** Format: date */
            effective_date: string;
            state_token: string;
        };
        /**
         * @description * `SUPPRIMER` - SUPPRIMER
         * @enum {string}
         */
        ConfirmationEnum: "SUPPRIMER";
        /**
         * @description * `accept` - accept
         *     * `reject` - reject
         * @enum {string}
         */
        DecisionEnum: "accept" | "reject";
        Draft: {
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            /** @default  */
            major_events: string;
            revision?: number | null;
        };
        /**
         * @description * `weekly` - weekly
         * @enum {string}
         */
        FrequencyEnum: "weekly";
        Generate: {
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            agenda_direction: components["schemas"]["AgendaDirectionEnum"];
        };
        Observation: {
            revision: number;
            message: string;
        };
        PatchedAvailabilityUpdate: {
            employee_id?: number;
            kind?: components["schemas"]["AvailabilityKindEnum"];
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** @default  */
            note: string;
            revision?: number;
        };
        PatchedMeProfile: {
            first_name?: string;
            last_name?: string;
            phone?: string;
            avatar?: string;
            terms_of_reference?: string;
        };
        /** @description Shared, server-validated assignment schedule. */
        PatchedProposalUpdate: {
            /** Format: date */
            start_date?: string;
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
            title?: string;
            description?: string;
            action_id?: number | null;
            calendar_id?: number;
            recurrence?: components["schemas"]["Recurrence"] | null;
            revision?: number;
        };
        /** @description Shared, server-validated assignment schedule. */
        PatchedTaskUpdate: {
            /** Format: date */
            start_date?: string;
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
            revision?: number;
            title?: string;
            description?: string;
            action_id?: number | null;
            recurrence?: components["schemas"]["Recurrence"] | null;
        };
        PatchedUserUpdate: {
            /** Format: email */
            email?: string;
            login_alias?: (string) | null;
            first_name?: string;
            last_name?: string;
            position?: string;
            phone?: string;
            agenda_direction?: components["schemas"]["AgendaDirectionEnum"] | components["schemas"]["BlankEnum"];
            /** @default true */
            include_in_direction_agendas: boolean;
            unit_ids?: number[];
            primary_unit_id?: number | null;
            primary_supervisor_id?: number | null;
            /** Format: date */
            organization_effective_date?: string;
            state_token?: string;
        };
        PlanningPreview: {
            calendar_id: number;
            /** Format: date */
            start_date: string;
            source: components["schemas"]["SourceEnum"];
            /** Format: date */
            due_date?: string;
            /** Format: decimal */
            estimated_work_days?: string;
            recurrence?: components["schemas"]["Recurrence"] | null;
        };
        Progress: {
            revision: number;
            /** Format: date */
            entry_date: string;
            percentage: number;
            /** @default  */
            note: string;
            /** @default false */
            blocked: boolean;
        };
        /** @description Shared, server-validated assignment schedule. */
        ProposalCreate: {
            /** Format: date */
            start_date: string;
            /** Format: date */
            due_date: string;
            /** Format: decimal */
            estimated_work_days: string;
            title: string;
            description: string;
            action_id?: number | null;
            calendar_id?: number;
            recurrence?: components["schemas"]["Recurrence"] | null;
        };
        ProposalDecision: {
            revision: number;
            decision: components["schemas"]["DecisionEnum"];
            /** @default  */
            reason: string;
        };
        ProposalResubmit: {
            revision: number;
        };
        Recurrence: {
            frequency: components["schemas"]["FrequencyEnum"];
            /** Format: date */
            end_date: string;
            revision?: number;
        };
        RecurrenceCancel: {
            revision: number;
            /** @default  */
            reason: string;
        };
        Revision: {
            revision: number;
        };
        /**
         * @description * `workload` - workload
         *     * `due` - due
         * @enum {string}
         */
        SourceEnum: "workload" | "due";
        StateToken: {
            state_token: string;
        };
        TaskBulkDelete: {
            assignments: components["schemas"]["TaskSelection"][];
            reason: string;
            confirmation: components["schemas"]["ConfirmationEnum"];
        };
        /** @description Shared, server-validated assignment schedule. */
        TaskCreate: {
            /** Format: date */
            start_date: string;
            /** Format: date */
            due_date: string;
            /** Format: decimal */
            estimated_work_days: string;
            title: string;
            description: string;
            employee_id: number;
            action_id?: number | null;
            calendar_id?: number;
            recurrence?: components["schemas"]["Recurrence"] | null;
        };
        TaskSelection: {
            id: number;
            revision: number;
        };
        TemporaryPasswordChange: {
            current_password: string;
            new_password: string;
            new_password_confirmation: string;
        };
        Transition: {
            revision: number;
            transition: components["schemas"]["TransitionEnum"];
            /** @default  */
            reason: string;
        };
        /**
         * @description * `validate` - validate
         *     * `reject` - reject
         *     * `close_early` - close_early
         * @enum {string}
         */
        TransitionEnum: "validate" | "reject" | "close_early";
        UserBulkAction: {
            action: components["schemas"]["ActionEnum"];
            users: components["schemas"]["UserSelection"][];
            reason?: string;
            /** @default  */
            confirmation: string;
        };
        UserSelection: {
            id: number;
            state_token: string;
        };
        UserWrite: {
            /** Format: email */
            email: string;
            login_alias?: (string) | null;
            first_name?: string;
            last_name?: string;
            position?: string;
            phone?: string;
            agenda_direction?: components["schemas"]["AgendaDirectionEnum"] | components["schemas"]["BlankEnum"];
            /** @default true */
            include_in_direction_agendas: boolean;
            unit_ids?: number[];
            primary_unit_id?: number | null;
            primary_supervisor_id?: number | null;
            /** Format: date */
            organization_effective_date: string;
            state_token?: string;
        };
        VisitCreate: {
            party_size: number;
            visitor_names?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agenda_draft_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Draft"];
                "application/x-www-form-urlencoded": components["schemas"]["Draft"];
                "multipart/form-data": components["schemas"]["Draft"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agenda_preview_retrieve: {
        parameters: {
            query?: {
                agenda_direction?: string;
                period_end?: string;
                period_start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agenda_versions_retrieve: {
        parameters: {
            query?: {
                agenda_direction?: string;
                period_end?: string;
                period_start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agenda_versions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Generate"];
                "application/x-www-form-urlencoded": components["schemas"]["Generate"];
                "multipart/form-data": components["schemas"]["Generate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agenda_versions_pdf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    availability_retrieve: {
        parameters: {
            query?: {
                week?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    availability_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Availability"];
                "application/x-www-form-urlencoded": components["schemas"]["Availability"];
                "multipart/form-data": components["schemas"]["Availability"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    availability_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAvailabilityUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAvailabilityUpdate"];
                "multipart/form-data": components["schemas"]["PatchedAvailabilityUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    availability_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cancel"];
                "application/x-www-form-urlencoded": components["schemas"]["Cancel"];
                "multipart/form-data": components["schemas"]["Cancel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboard_retrieve: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    my_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    my_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMeProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMeProfile"];
                "multipart/form-data": components["schemas"]["PatchedMeProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    planning_options_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    planning_preview_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningPreview"];
                "application/x-www-form-urlencoded": components["schemas"]["PlanningPreview"];
                "multipart/form-data": components["schemas"]["PlanningPreview"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalCreate"];
                "multipart/form-data": components["schemas"]["ProposalCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProposalUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProposalUpdate"];
                "multipart/form-data": components["schemas"]["PatchedProposalUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_decision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecision"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalDecision"];
                "multipart/form-data": components["schemas"]["ProposalDecision"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proposal_resubmit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalResubmit"];
                "application/x-www-form-urlencoded": components["schemas"]["ProposalResubmit"];
                "multipart/form-data": components["schemas"]["ProposalResubmit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemporaryPasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["TemporaryPasswordChange"];
                "multipart/form-data": components["schemas"]["TemporaryPasswordChange"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    task_management_retrieve: {
        parameters: {
            query?: {
                employee_id?: number;
                page?: number;
                page_size?: number;
                q?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    task_recurrences_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurrenceCancel"];
                "application/x-www-form-urlencoded": components["schemas"]["RecurrenceCancel"];
                "multipart/form-data": components["schemas"]["RecurrenceCancel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskCreate"];
                "multipart/form-data": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTaskUpdate"];
                "multipart/form-data": components["schemas"]["PatchedTaskUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_observations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Observation"];
                "application/x-www-form-urlencoded": components["schemas"]["Observation"];
                "multipart/form-data": components["schemas"]["Observation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_progress_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Progress"];
                "application/x-www-form-urlencoded": components["schemas"]["Progress"];
                "multipart/form-data": components["schemas"]["Progress"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
                "application/x-www-form-urlencoded": components["schemas"]["Transition"];
                "multipart/form-data": components["schemas"]["Transition"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tasks_bulk_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskBulkDelete"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskBulkDelete"];
                "multipart/form-data": components["schemas"]["TaskBulkDelete"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    team_overview: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    team_employee_detail: {
        parameters: {
            query?: {
                month?: string;
                week?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    user_list: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                q?: string;
                state?: string;
                unit_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    user_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["UserWrite"];
                "multipart/form-data": components["schemas"]["UserWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    user_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_activation_link_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateToken"];
                "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
                "multipart/form-data": components["schemas"]["StateToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_collaborators_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_collaborators_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollaboratorUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CollaboratorUpdate"];
                "multipart/form-data": components["schemas"]["CollaboratorUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_deactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateToken"];
                "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
                "multipart/form-data": components["schemas"]["StateToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_reactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateToken"];
                "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
                "multipart/form-data": components["schemas"]["StateToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_temporary_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateToken"];
                "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
                "multipart/form-data": components["schemas"]["StateToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_bulk_action: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBulkAction"];
                "application/x-www-form-urlencoded": components["schemas"]["UserBulkAction"];
                "multipart/form-data": components["schemas"]["UserBulkAction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    user_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    visits_retrieve: {
        parameters: {
            query?: {
                period_end?: string;
                period_start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    visits_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["VisitCreate"];
                "multipart/form-data": components["schemas"]["VisitCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    visits_departure_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Revision"];
                "application/x-www-form-urlencoded": components["schemas"]["Revision"];
                "multipart/form-data": components["schemas"]["Revision"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
