from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.core.validators
import simple_history.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="WeeklyAgendaDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField(unique=True)),
                ("major_events", models.TextField(blank=True, verbose_name="événements majeurs")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_weekly_agenda_drafts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-week_start"]},
        ),
        migrations.CreateModel(
            name="VisitorVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("arrived_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="arrivée")),
                ("departed_at", models.DateTimeField(blank=True, null=True, verbose_name="départ")),
                ("party_size", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="nombre de visiteurs")),
                ("visitor_names", models.JSONField(blank=True, default=list, verbose_name="noms facultatifs")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recorded_visitor_visits", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_visitor_visits", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-arrived_at", "-pk"]},
        ),
        migrations.CreateModel(
            name="StaffAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("leave", "Congé"), ("absence", "Absence"), ("mission", "Mission")], max_length=12)),
                ("start_date", models.DateField(verbose_name="début")),
                ("end_date", models.DateField(verbose_name="fin")),
                ("note", models.TextField(blank=True, verbose_name="observation")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="availability_periods", to=settings.AUTH_USER_MODEL)),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recorded_availability_periods", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updated_availability_periods", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["start_date", "employee", "kind"]},
        ),
        migrations.CreateModel(
            name="HistoricalWeeklyAgendaDraft",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("week_start", models.DateField(db_index=True)),
                ("major_events", models.TextField(blank=True, verbose_name="événements majeurs")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "historical weekly agenda draft", "verbose_name_plural": "historical weekly agenda drafts", "ordering": ("-history_date", "-history_id"), "get_latest_by": ("history_date", "history_id")},
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisitorVisit",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("arrived_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="arrivée")),
                ("departed_at", models.DateTimeField(blank=True, null=True, verbose_name="départ")),
                ("party_size", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="nombre de visiteurs")),
                ("visitor_names", models.JSONField(blank=True, default=list, verbose_name="noms facultatifs")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("recorded_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "historical visitor visit", "verbose_name_plural": "historical visitor visits", "ordering": ("-history_date", "-history_id"), "get_latest_by": ("history_date", "history_id")},
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStaffAvailability",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("kind", models.CharField(choices=[("leave", "Congé"), ("absence", "Absence"), ("mission", "Mission")], max_length=12)),
                ("start_date", models.DateField(verbose_name="début")),
                ("end_date", models.DateField(verbose_name="fin")),
                ("note", models.TextField(blank=True, verbose_name="observation")),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("employee", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("recorded_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "historical staff availability", "verbose_name_plural": "historical staff availabilitys", "ordering": ("-history_date", "-history_id"), "get_latest_by": ("history_date", "history_id")},
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WeeklyAgendaVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField()),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("storage_provider", models.CharField(max_length=24)),
                ("storage_key", models.CharField(max_length=500)),
                ("pdf_sha256", models.CharField(max_length=64)),
                ("pdf_size", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("draft", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="agenda.weeklyagendadraft")),
                ("generated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_weekly_agendas", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-week_start", "-version"]},
        ),
        migrations.AddConstraint(model_name="visitorvisit", constraint=models.CheckConstraint(condition=models.Q(("departed_at__isnull", True), ("departed_at__gte", models.F("arrived_at")), _connector="OR"), name="visitor_departure_not_before_arrival")),
        migrations.AddConstraint(model_name="visitorvisit", constraint=models.CheckConstraint(condition=models.Q(models.Q(("cancelled_at__isnull", True), ("cancellation_reason", "")), models.Q(("cancelled_at__isnull", False), models.Q(("cancellation_reason", ""), _negated=True)), _connector="OR"), name="visitor_cancellation_has_reason")),
        migrations.AddConstraint(model_name="staffavailability", constraint=models.CheckConstraint(condition=models.Q(("end_date__gte", models.F("start_date"))), name="availability_end_not_before_start")),
        migrations.AddConstraint(model_name="staffavailability", constraint=models.CheckConstraint(condition=models.Q(models.Q(("cancelled_at__isnull", True), ("cancellation_reason", "")), models.Q(("cancelled_at__isnull", False), models.Q(("cancellation_reason", ""), _negated=True)), _connector="OR"), name="availability_cancellation_has_reason")),
        migrations.AddConstraint(model_name="weeklyagendaversion", constraint=models.UniqueConstraint(fields=("week_start", "version"), name="unique_weekly_agenda_version")),
    ]
