# Generated by Django 5.2.16 on 2026-07-11 09:35

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='nom')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='date')),
                ('name', models.CharField(max_length=180, verbose_name='libelle')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='debut')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='nom')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='work.actionplan')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTaskProposal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='debut')),
                ('due_date', models.DateField(verbose_name='echeance')),
                ('estimated_work_days', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='charge estimee en jours')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('accepted', 'Acceptee'), ('rejected', 'Rejetee')], default='submitted', max_length=16)),
                ('decision_note', models.TextField(blank=True, verbose_name='motif')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.institutionalaction')),
            ],
            options={
                'verbose_name': 'historical task proposal',
                'verbose_name_plural': 'historical task proposals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='code interne')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.institutionalaction')),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='work.organizationunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReportingLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='responsable principal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.organizationunit')),
            ],
            options={
                'verbose_name': 'historical reporting line',
                'verbose_name_plural': 'historical reporting lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='strategic_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='work.strategicplan'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code interne')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='work.institutionalaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaskAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='debut')),
                ('due_date', models.DateField(verbose_name='echeance')),
                ('estimated_work_days', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='charge estimee en jours')),
                ('status', models.CharField(choices=[('planned', 'Planifiee'), ('active', 'En cours'), ('awaiting_validation', 'A valider'), ('completed', 'Terminee'), ('closed_early', 'Cloturee avant achevement')], default='planned', max_length=24, verbose_name='etat')),
                ('closed_reason', models.TextField(blank=True, verbose_name='motif de cloture')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.task')),
            ],
            options={
                'verbose_name': 'historical task assignment',
                'verbose_name_plural': 'historical task assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='debut')),
                ('due_date', models.DateField(verbose_name='echeance')),
                ('estimated_work_days', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='charge estimee en jours')),
                ('status', models.CharField(choices=[('planned', 'Planifiee'), ('active', 'En cours'), ('awaiting_validation', 'A valider'), ('completed', 'Terminee'), ('closed_early', 'Cloturee avant achevement')], default='planned', max_length=24, verbose_name='etat')),
                ('closed_reason', models.TextField(blank=True, verbose_name='motif de cloture')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='work.task')),
            ],
            options={
                'ordering': ['due_date', 'task__title'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='date')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement')),
                ('note', models.TextField(blank=True, verbose_name='observation')),
                ('blocked', models.BooleanField(default=False, verbose_name='blocage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='work.taskassignment')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProgressEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='date')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement')),
                ('note', models.TextField(blank=True, verbose_name='observation')),
                ('blocked', models.BooleanField(default=False, verbose_name='blocage')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.taskassignment')),
            ],
            options={
                'verbose_name': 'historical progress entry',
                'verbose_name_plural': 'historical progress entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.taskassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(verbose_name='debut')),
                ('due_date', models.DateField(verbose_name='echeance')),
                ('estimated_work_days', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='charge estimee en jours')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('accepted', 'Acceptee'), ('rejected', 'Rejetee')], default='submitted', max_length=16)),
                ('decision_note', models.TextField(blank=True, verbose_name='motif')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.institutionalaction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_proposals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='responsable principal')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_lines', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_lines', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_lines', to='work.organizationunit')),
            ],
            options={
                'ordering': ['employee', '-is_primary', '-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('employee', models.F('supervisor')), _negated=True), name='reporting_line_distinct_people'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='reporting_line_valid_dates'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('employee',), name='one_active_primary_supervisor')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='assignment_due_after_start'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'employee'), name='unique_task_employee_assignment'),
        ),
        migrations.AddConstraint(
            model_name='progressentry',
            constraint=models.UniqueConstraint(fields=('assignment', 'entry_date'), name='one_progress_per_assignment_day'),
        ),
        migrations.AddConstraint(
            model_name='taskproposal',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='proposal_due_after_start'),
        ),
    ]
