# Generated by Django 5.2.16 on 2026-07-12 21:01

import django.db.models.deletion
import django.utils.timezone
import work.models
from datetime import date, timedelta
from decimal import Decimal
from math import ceil
from django.conf import settings
from django.db import migrations, models


def prepare_defaults(apps, schema_editor):
    StrategicPlan = apps.get_model("work", "StrategicPlan")
    ActionPlan = apps.get_model("work", "ActionPlan")
    InstitutionalAction = apps.get_model("work", "InstitutionalAction")
    WorkCalendar = apps.get_model("work", "WorkCalendar")
    plan, _ = StrategicPlan.objects.get_or_create(
        name="Classification transitoire",
        defaults={"start_date": date(2024, 1, 1), "end_date": date(2028, 12, 31)},
    )
    action_plan, _ = ActionPlan.objects.get_or_create(
        code="PA-TRANSITOIRE",
        defaults={"name": "Activites a reclasser", "strategic_plan": plan},
    )
    fallback, _ = InstitutionalAction.objects.get_or_create(
        code="ACT-TRANSITOIRE",
        defaults={"name": "Activites a reclasser", "action_plan": action_plan},
    )
    apps.get_model("work", "Task").objects.filter(action__isnull=True).update(
        action=fallback
    )
    apps.get_model("work", "TaskProposal").objects.filter(action__isnull=True).update(
        action=fallback
    )
    WorkCalendar.objects.get_or_create(
        name="Cote d'Ivoire",
        version="CI-2026-decret-2011-371-v1",
        defaults={"is_default": True, "active": True},
    )


def seed_calendar_and_normalize(apps, schema_editor):
    WorkCalendar = apps.get_model("work", "WorkCalendar")
    WorkCalendarDay = apps.get_model("work", "WorkCalendarDay")
    calendar = WorkCalendar.objects.get(is_default=True)
    holidays = (
        (date(2026, 1, 1), "Jour de l'An"),
        (date(2026, 3, 16), "Lendemain de la Nuit du Destin"),
        (date(2026, 3, 20), "Aïd el-Fitr — date annuelle de reference"),
        (date(2026, 4, 6), "Lundi de Paques"),
        (date(2026, 5, 1), "Fete du Travail"),
        (date(2026, 5, 14), "Ascension"),
        (date(2026, 5, 25), "Lundi de Pentecote"),
        (date(2026, 5, 27), "Tabaski — date annuelle de reference"),
        (date(2026, 8, 7), "Fete nationale"),
        (date(2026, 8, 15), "Assomption"),
        (date(2026, 8, 26), "Maouloud — date annuelle de reference"),
        (date(2026, 11, 1), "Toussaint"),
        (date(2026, 11, 15), "Journee nationale de la Paix"),
        (date(2026, 12, 25), "Noel"),
    )
    for day, name in holidays:
        WorkCalendarDay.objects.get_or_create(
            calendar=calendar,
            day=day,
            defaults={"name": name, "is_working_day": False},
        )
    blocked = set(
        WorkCalendarDay.objects.filter(calendar=calendar, is_working_day=False)
        .values_list("day", flat=True)
    )
    opened = set(
        WorkCalendarDay.objects.filter(calendar=calendar, is_working_day=True)
        .values_list("day", flat=True)
    )

    def due_for(start, workload):
        remaining = ceil(Decimal(workload))
        cursor = start
        while remaining:
            cursor += timedelta(days=1)
            working = cursor in opened or (cursor.weekday() < 5 and cursor not in blocked)
            if working:
                remaining -= 1
        return cursor

    for model_name in ("TaskAssignment", "TaskProposal"):
        model = apps.get_model("work", model_name)
        for item in model.objects.all().iterator():
            item.calendar = calendar
            item.due_date = due_for(item.start_date, item.estimated_work_days)
            item.save(update_fields=["calendar", "due_date"])


def migrate_activity_feed(apps, schema_editor):
    TaskActivity = apps.get_model("work", "TaskActivity")
    for comment in apps.get_model("work", "TaskComment").objects.all().iterator():
        TaskActivity.objects.create(
            assignment_id=comment.assignment_id,
            kind="comment",
            actor_id=comment.author_id,
            occurred_at=comment.created_at,
            message=comment.body,
        )
    for progress in apps.get_model("work", "ProgressEntry").objects.exclude(note="").iterator():
        TaskActivity.objects.create(
            assignment_id=progress.assignment_id,
            kind="progress",
            actor_id=progress.author_id,
            occurred_at=progress.updated_at,
            message=progress.note,
            percentage_after=progress.percentage,
            progress_entry_id=progress.pk,
        )


class Migration(migrations.Migration):

    # PostgreSQL cannot alter the action foreign keys while the data migrations
    # above still have deferred trigger events in the same transaction.
    atomic = False

    dependencies = [
        ('work', '0004_alter_taskproposal_status_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('version', models.CharField(max_length=32, verbose_name='version')),
                ('is_default', models.BooleanField(default=False, verbose_name='calendrier par defaut')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_work_calendar_version'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_work_calendar')],
            },
        ),
        migrations.RunPython(prepare_defaults, migrations.RunPython.noop),
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='calendar',
            field=models.ForeignKey(blank=True, db_constraint=False, default=work.models.default_work_calendar_id, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.workcalendar'),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='calendar',
            field=models.ForeignKey(blank=True, db_constraint=False, default=work.models.default_work_calendar_id, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.workcalendar'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='calendar',
            field=models.ForeignKey(default=work.models.default_work_calendar_id, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work.workcalendar'),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='calendar',
            field=models.ForeignKey(default=work.models.default_work_calendar_id, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='work.workcalendar'),
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('progress', 'Progression'), ('comment', 'Observation'), ('validated', 'Achevement valide'), ('rejected', 'Reprise demandee'), ('reopened', 'Tache rouverte'), ('closed', 'Tache cloturee'), ('schedule', 'Planification modifiee')], max_length=24, verbose_name='type')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('message', models.TextField(verbose_name='observation')),
                ('percentage_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='work.taskassignment')),
                ('progress_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='work.progressentry')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='work.taskactivity')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
                'indexes': [models.Index(fields=['assignment', 'occurred_at'], name='work_taskac_assignm_24ecfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='annee')),
                ('next_value', models.PositiveIntegerField(default=1, verbose_name='prochain numero')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_sequences', to='work.institutionalaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action', 'year'), name='one_task_sequence_per_action_year')],
            },
        ),
        migrations.CreateModel(
            name='WorkCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=180, verbose_name='libelle')),
                ('is_working_day', models.BooleanField(default=False, verbose_name='jour ouvre')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='work.workcalendar')),
            ],
            options={
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'day'), name='one_override_per_calendar_day')],
            },
        ),
        migrations.RunPython(seed_calendar_and_normalize, migrations.RunPython.noop),
        migrations.RunPython(migrate_activity_feed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='work.institutionalaction'),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.institutionalaction'),
        ),
    ]
