# Generated by Django 5.2.16 on 2026-07-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_task_action_alter_taskproposal_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
