# Generated by Django 5.2.16 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("work", "0007_add_2026_night_of_destiny")]

    operations = [
        migrations.CreateModel(
            name="ProgressSeriesCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "through_date",
                    models.DateField(verbose_name="serie calculee jusqu'au"),
                ),
                ("payload", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_series_cache",
                        to="work.taskassignment",
                    ),
                ),
            ],
            options={"ordering": ["assignment_id"]},
        )
    ]
