# Generated by Django 5.2.16 on 2026-07-17 05:53

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_optional_action_and_tenth_day_workload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='organization_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.organizationunit', verbose_name='service historique'),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='organization_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.organizationunit', verbose_name='service historique'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='work.organizationunit', verbose_name='service historique'),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_proposals', to='work.organizationunit', verbose_name='service historique'),
        ),
        migrations.CreateModel(
            name='HistoricalOrganizationMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=160, verbose_name='fonction dans le service')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='appartenance principale')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.organizationunit')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical organization membership',
                'verbose_name_plural': 'historical organization memberships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=160, verbose_name='fonction dans le service')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('is_primary', models.BooleanField(default=False, verbose_name='appartenance principale')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='work.organizationunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-is_primary', '-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='organization_membership_valid_dates'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('user',), name='one_open_primary_membership')],
            },
        ),
    ]
