# Generated by Django 5.2.16 on 2026-07-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_backfill_organization_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='work.organizationunit', verbose_name='service historique'),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_proposals', to='work.organizationunit', verbose_name='service historique'),
        ),
    ]
