# Generated by Django 5.2.16 on 2026-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_alter_taskassignment_organization_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
