# Generated by Django 5.2.16 on 2026-08-25 11:48

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_precise_workload_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='recurrence_anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='recurrence_occurrence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Chaque semaine')], max_length=16),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='recurrence_anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='recurrence_occurrence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Chaque semaine')], max_length=16),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='kind',
            field=models.CharField(choices=[('progress', 'Progression'), ('comment', 'Observation'), ('validated', 'Achevement valide'), ('rejected', 'Reprise demandee'), ('reopened', 'Tache rouverte'), ('closed', 'Tache cloturee'), ('schedule', 'Planification modifiee'), ('recurrence', 'Repetition')], max_length=24, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='HistoricalTaskRecurrence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('estimated_work_days', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='charge estimee en jours')),
                ('frequency', models.CharField(choices=[('weekly', 'Chaque semaine')], default='weekly', max_length=16)),
                ('anchor_start_date', models.DateField(verbose_name="date d'ancrage")),
                ('end_date', models.DateField(verbose_name='fin inclusive')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Terminee'), ('cancelled', 'Annulee')], default='active', max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.institutionalaction')),
                ('calendar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.workcalendar')),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical task recurrence',
                'verbose_name_plural': 'historical task recurrences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom court')),
                ('description', models.TextField(verbose_name='description')),
                ('estimated_work_days', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='charge estimee en jours')),
                ('frequency', models.CharField(choices=[('weekly', 'Chaque semaine')], default='weekly', max_length=16)),
                ('anchor_start_date', models.DateField(verbose_name="date d'ancrage")),
                ('end_date', models.DateField(verbose_name='fin inclusive')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Terminee'), ('cancelled', 'Annulee')], default='active', max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_recurrences', to='work.institutionalaction')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_recurrences', to='work.workcalendar')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_task_recurrences', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_recurrences', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_recurrences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historicaltaskassignment',
            name='recurrence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.taskrecurrence'),
        ),
        migrations.AddField(
            model_name='historicaltaskproposal',
            name='accepted_recurrence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.taskrecurrence'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work.taskrecurrence'),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='accepted_recurrence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_proposal', to='work.taskrecurrence'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence__isnull', False)), fields=('recurrence', 'recurrence_occurrence'), name='unique_task_recurrence_occurrence'),
        ),
    ]
