# Generated by Django 5.2.16 on 2026-07-11 12:26

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_alias',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Utilisez des lettres minuscules, chiffres, tirets ou underscores.', regex='^[a-z][a-z0-9_-]*$')], verbose_name='identifiant court'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('login_alias'), condition=models.Q(('login_alias__isnull', False)), name='unique_login_alias_ci'),
        ),
    ]
