# Generated by Django 5.2.16 on 2026-08-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_populate_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='agenda_direction',
            field=models.CharField(blank=True, choices=[('programs', 'Direction des programmes'), ('administration', 'Direction administrative')], default='', help_text='Une personne non classée et toutes ses tâches figurent provisoirement dans les deux agendas.', max_length=16, verbose_name="direction de l'agenda"),
        ),
        migrations.AddField(
            model_name='user',
            name='agenda_direction',
            field=models.CharField(blank=True, choices=[('programs', 'Direction des programmes'), ('administration', 'Direction administrative')], default='', help_text='Une personne non classée et toutes ses tâches figurent provisoirement dans les deux agendas.', max_length=16, verbose_name="direction de l'agenda"),
        ),
    ]
