# Generated by Django 5.2.16 on 2026-07-17 05:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0014_backfill_organization_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scoped_role', to='auth.group', verbose_name='groupe de permissions')),
            ],
            options={
                'ordering': ['code'],
                'permissions': [('view_unit_scope', "Consulter les donnees d'un service"), ('manage_unit_assignments', "Gerer les taches d'un service"), ('correct_unit_progress', "Corriger la progression d'un service"), ('review_unit_proposals', "Decider les propositions d'un service"), ('export_unit_data', "Exporter les donnees d'un service")],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoleGrant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scope', models.CharField(choices=[('unit', 'Ce service uniquement'), ('tree', 'Ce service et ses sous-services')], default='tree', max_length=8, verbose_name='portee')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='valide a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('grant_reason', models.TextField(verbose_name="motif de l'attribution")),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoquee le')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='motif de la revocation')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.organizationunit')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='access.scopedrole')),
            ],
            options={
                'verbose_name': 'historical role grant',
                'verbose_name_plural': 'historical role grants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('unit', 'Ce service uniquement'), ('tree', 'Ce service et ses sous-services')], default='tree', max_length=8, verbose_name='portee')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='valide a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('grant_reason', models.TextField(verbose_name="motif de l'attribution")),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoquee le')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='motif de la revocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_role_grants', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_role_grants', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_grants', to='work.organizationunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access.scopedrole')),
            ],
            options={
                'ordering': ['-valid_from', 'user', 'role'],
                'indexes': [models.Index(fields=['user', 'valid_from', 'valid_until'], name='access_role_user_id_e15ecb_idx'), models.Index(fields=['unit', 'role'], name='access_role_unit_id_7fc92b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='role_grant_valid_window'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False)), _connector='OR'), name='role_grant_revocation_actor')],
            },
        ),
    ]
